---
resources:
    - name: source-code
      type: git
      source: 
         uri: https://github.com/rishvantsingh/spring_boot_concourse.git
         branch: master
jobs:
    - name: clean-test
      plan:
        -  get: source-code
           trigger: true
        -  task: maven-exec
           config:
              platform: linux
              image_resource:
                   type: docker-image
                   source:
                      repository: maven
              inputs: 
                 - name: source-code
              run:
                   path: source-code/ci/script.sh
    -  name: package
       plan: 
             - get: source-code
               passed: [clean-test]
               trigger: true
             - task: package
               file: source-code/ci/task-package.yml

             - task: find-all
               config:
                  platform: linux
                  image_resource:
                     type: docker-image
                     source: {repository: openjdk}
                    
                  inputs:
                      - name: target

                  run:
                    path: java
                    args:
                      - -jar
                      -  target/hello-0.0.1-SNAPSHOT.jar



